### ISSUE TITLE
Issues running example app

### ISSUE THREAD

**Issue by moovida** [mikes222/mapsforge_flutter#16] opened 2021-01-22 07:59 UTC
Some exceptions I found running the example app on a pixel 2XL:

## OFFLINE MONACO

```
/flutter (19946): Download Error - DioError [DioErrorType.DEFAULT]: Bad state: Insecure HTTP is not allowed by platform: http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/v5/europe/monaco.map
I/flutter (19946): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2435:7)
I/flutter (19946): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2342:7)
I/flutter (19946): #2      DefaultHttpClientAdapter.fetch
package:dio/…/adapters/io_adapter.dart:35
I/flutter (19946): #3      DioMixin._dispatchRequest
package:dio/src/dio.dart:922
I/flutter (19946): <asynchronous suspension>
I/flutter (19946): #4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart)
package:dio/src/dio.dart:1
...
```

## Indoor Chemnitz

This happens only the first time the app is accessed (had to uninstall to reproduce), but it crashes the app. If restarting the app, it works as expected.

```
W/chwartz.exampl(24412): Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
W/chwartz.exampl(24412): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/chwartz.exampl(24412): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
W/chwartz.exampl(24412): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
I/flutter (24412): 2021-01-22 08:39:04.163927	RenderThemeBuilder	[INFO]:	Found 67 items for lazy initialization
I/flutter (24412): Creating directory /data/user/0/com.mschwartz.example/cache/mapsforgetiles/1269
I/flutter (24412): 2021-01-22 08:39:04.767361	FileTileBitmapCache	[INFO]:	Starting cache for renderkey 1269 with 0 items in filecache
F/libc    (24412): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x70e00000007cf097 in tid 24482 (DartWorker), pid 24412 (chwartz.example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/taimen/taimen:10/QP1A.191005.007.A1/5908163:user/release-keys'
Revision: 'rev_10'
ABI: 'arm64'
Timestamp: 2021-01-22 08:39:05+0100
pid: 24412, tid: 24482, name: DartWorker  >>> com.mschwartz.example <<<
uid: 10325
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x70e00000007cf097
    x0  0000000000000001  x1  00000000000000ea  x2  00000000000000ea  x3  0000007c93f20bbe
    x4  0000007c6e294f08  x5  0000007c6e2a0048  x6  0000007cf087ec98  x7  0000007c6e346228
    x8  0000007cf087ec9a  x9  0000000000000002  x10 0000007cf0814878  x11 9ddfea08eb382d69
    x12 0000000000000000  x13 0000000000000018  x14 ffffffffffffffff  x15 000000000000000e
    x16 0000007c958190b0  x17 0000007d819a5380  x18 0000007c80d28000  x19 0000007c81c7afa0
    x20 0000000000000004  x21 0000000000000001  x22 00000000000000ea  x23 0000000000000000
    x24 0000007cf0814878  x25 0000000000000004  x26 0000007cf17864f0  x27 0000000000000018
    x28 1000000000000000  x29 70e00000007cf087
    sp  0000007c81c7ae80  lr  0000007c956edec4  pc  0000007c956eddf0
backtrace:
      #00 pc 0000000001967df0  /data/app/com.mschwartz.example-FEtPWgNZNUYlzHsJDxzLNw==/lib/arm64/libflutter.so (BuildId: 071260c46554f7fe803a0e685f6a5bad8159a148)
      #01 pc 0000000001967ec0  /data/app/com.mschwartz.example-FEtPWgNZNUYlzHsJDxzLNw==/lib/arm64/libflutter.so (BuildId: 071260c46554f7fe803a0e685f6a5bad8159a148)
      #02 pc 0000000000000186  <unknown>
Lost connection to device.
```

## General warnings

While rendering indoor I get many:
```
I/flutter (24791): 2021-01-22 08:41:42.182697	FlutterBitmap	[WARNING]:	Bitmap [256×256] refcount is 30
I/flutter (24791): 2021-01-22 08:41:42.183012	FlutterBitmap	[WARNING]:	Bitmap [256×256] refcount is 40
I/flutter (24791): 2021-01-22 08:41:42.199119	FlutterBitmap	[WARNING]:	Bitmap [256×256] refcount is 30
I/flutter (24791): 2021-01-22 08:41:42.216048	FlutterBitmap	[WARNING]:	Bitmap [256×256] refcount is 40
I/flutter (24791): 2021-01-22 08:41:42.265491	FlutterBitmap	[WARNING]:	Bitmap [256×256] refcount is 40
I/flutter (24791): 2021-01-22 08:41:42.265777	FlutterBitmap	[WARNING]:	Bitmap [256×256] refcount is 60
```

**Comment by mikes222** [comment] 2021-01-23 19:31
Thanks for enumerating the problems. 
ad 1: I moved monaco to one of my own servers with https so this should not occur anymore
ad 2: It seems like a problem with flutter itself. Hope it does not occur in production. Unfortunately I do not see anything currently to tackle that problem
ad 3: I pushed a new version where this problem is reduced (though not fully solved yet). I will work on it later on. The problem is that images needs to be destroyed when they are not used. In this case the images are never marked as "not used" so the memory is not freed as it could be. 

If you find more issues feel free to report them.

**Closed by mikes222** 2021-01-23 19:31 UTC
